/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XyButton {
    }
}
declare global {
    interface HTMLXyButtonElement extends Components.XyButton, HTMLStencilElement {
    }
    var HTMLXyButtonElement: {
        prototype: HTMLXyButtonElement;
        new (): HTMLXyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "xy-button": HTMLXyButtonElement;
    }
}
declare namespace LocalJSX {
    interface XyButton {
    }
    interface IntrinsicElements {
        "xy-button": XyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xy-button": LocalJSX.XyButton & JSXBase.HTMLAttributes<HTMLXyButtonElement>;
        }
    }
}
